version: "3.7"

services:
  db:
    image: mariadb:10.9
    environment:
      - 'MYSQL_USER=root'
      - 'MYSQL_ROOT_PASSWORD=123456'
      - 'MYSQL_DATABASE=spsvo_db'
    ports:
      - "3306:3306"
    restart: on-failure