version: "3.7"

services:
  db:
    image: mariadb:10.9
    environment:
      - 'MYSQL_USER=root'
      - 'MYSQL_ROOT_PASSWORD=123456'
      - 'MYSQL_DATABASE=spsvo'
    ports:
      - "3306:3306"
    restart: on-failure

  app:
    image: spsvo
    depends_on:
      - db
    ports:
      - "8080:8080"
    links:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://db/spsvo
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
    restart: on-failure